# Используем базовый образ Arch Linux
FROM archlinux:latest

# Обновляем систему и устанавливаем необходимые пакеты
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm nginx openssl

# Создаем директории для сертификатов и HTML
RUN mkdir -p /etc/ssl/certs /etc/ssl/private /usr/share/nginx/html

# Создаем самоподписанный сертификат и ключ
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/selfsigned.key \
    -out /etc/ssl/certs/selfsigned.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost"

# Копируем конфигурационный файл Nginx
COPY templates/nginx.conf /etc/nginx/nginx.conf

# Открываем порты
EXPOSE 80 443

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]